config/routes.rb
Rails.application.routes.draw do
  root "tasks#mine"
  
  resources :tasks do
    get 'mine', on: :collection
    get 'assign', on: :member
    patch 'assign_update', on: :member
  end
  
  devise_for :users
 
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true, 
                    length: { maximum: 100 } 
  validates :status, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name)

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
    devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_task, only: [:show, :edit, :update, :destroy, :assign]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where.not(status: 3)
  end
  
  def mine
    @tasks = current_user.tasks.where.not(status: 3)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    if @task.user_id != current_user.id
      redirect_to tasks_url, alert: "タスクを編集できません"
    end
  end
  
  def assign
    @task = Task.find(params[:id])
    if @task.user_id != current_user.id
      redirect_to tasks_url, alert: "タスクを編集できません"
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, notice: 'タスクが作成されました'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
     @task = Task.find(params[:id])
    if @task.user_id != current_user.id
      redirect_to tasks_url, alert: "タスクを編集できません"
    end
    
    if @task.update(task_params)
      redirect_to @task, notice: 'タスクが更新されました'
    else
      render :edit
    end
  end
  
  def assign_update
    @task = Task.find(params[:id])
    if @task.user_id != current_user.id
      redirect_to tasks_url, alert: "タスクを編集できません"
    end
    
    if @task.update(charge_id: params[:task][:charge_id])
      redirect_to @task, notice: 'タスクが新しくアサインされました'
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
     @task = Task.find(params[:id])
    if @task.user_id != current_user.id
      redirect_to tasks_url, alert: "タスクを編集できません"
    end
    
    @task.destroy
    redirect_to tasks_url, notice: 'タスクが削除されました'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_status(status)
    if status == 1
      "未対応"
    elsif status == 2
      "対応中"
    elsif status == 3
      "完了"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarEexample8">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">
				タスク管理アプリ
			</a>
		</div>
		
		<div class="collapse navbar-collapse" id="navbarEexample8">
			<ul class="nav navbar-nav">
				<li><%= link_to 'マイタスク', mine_tasks_path %></li>
				<li><%= link_to 'タスク一覧', tasks_path %></li>
				<li><%= link_to 'ユーザ設定', edit_user_registration_path %></li>
				<li><%= link_to '', edit_user_registration_path %></li>
				<% if user_signed_in? %>
				  <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete %></li>
				<% else %>
  			  <li><%= link_to 'サインイン', new_user_session_path %></li>
  			<% end %>
			</ul>
			<% if user_signed_in? %>
			  <p class="navbar-text navbar-right">ようこそ<%= current_user.name %>さん</p>
			<% end %>
		</div>
	</div>
</nav>

<div class="container">
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <%= yield %>
</div>


</body>
</html>

app/views/tasks/assign.html.erb
<h1>アサイン</h1>

<%= form_for(@task, url: assign_update_task_path) do |f| %>
  <div class="col-md-6 col-xs-12">
    <p>現在アサインされているユーザ</p>
    <p><%= @task.user.name %></p>
  </div>

  <div class="col-md-6 col-xs-12">
    <p>新しくアサインするユーザ</p>
    <%= f.collection_select :user_id, User.all, :id, :name, {}, class: 'form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit "アサインする", class: 'btn btn-success' %>
  </div>
<% end %>

<div class="jumbotron">
	<h1><%= @task.title %></h1>
	<p><%= @task.content %></p>
	<p>期限：<%= @task.deadline %></p>
	<p>ステータス：<%= display_status(@task.status) %></p>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  
  <div class="field">
    <%= f.label :status %>
    <span><%= f.radio_button :status, 1 %>未対応</span>
    <span><%= f.radio_button :status, 2 %>対応中</span>
    <span><%= f.radio_button :status, 3 %>完了</span>
  </div>
  
  <div class="actions">
    <%= f.submit "更新する", class: 'btn btn-success' %>
    <%= link_to '一覧へ戻る', tasks_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-6 col-xs-12">
    <% if task.deadline < Time.now %>
      <div class="panel panel-danger">
    <% else %>
      <div class="panel panel-success">
    <% end %>
      	<div class="panel-heading">
      		<%= task.title %>
      	</div>
      	<div class="panel-body">
      		<%= task.content %>
      		<p>期限：<%= task.deadline.strftime("%Y年%m月%d日") %></p>
          <p>担当者：<%= task.user.name %></p>
          <p>ステータス：<%= display_status(task.status) %></p>
          <p>
            <%= link_to '詳細', task, class: 'btn btn-default' %>
            <% if task.user == current_user %>
              <%= link_to '編集', edit_task_path(task), class: 'btn btn-info' %>
              <%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </p>
      	</div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/mine.html.erb
<h1>マイタスク</h1>

<%= link_to 'New Task', new_task_path, class: 'btn btn-default' %>

<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-6 col-xs-12">
    <% if task.deadline < Time.now %>
      <div class="panel panel-danger">
    <% else %>
      <div class="panel panel-success">
    <% end %>
      	<div class="panel-heading">
      		<%= task.title %>
      	</div>
      	<div class="panel-body">
      		<%= task.content %>
      		<p>期限：<%= task.deadline.strftime("%Y年%m月%d日") %></p>
          <p>担当者：<%= task.user.name %></p>
          <p>ステータス：<%= display_status(task.status) %></p>
          <p>
            <%= link_to '詳細', task, class: 'btn btn-default' %>
            <% if task.user == current_user %>
              <%= link_to '編集', edit_task_path(task), class: 'btn btn-info' %>
              <%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </p>
      	</div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  
  <div class="field">
    <%= f.label :status %>
    <span><%= f.radio_button :status, 1 %>未対応</span>
    <span><%= f.radio_button :status, 2 %>対応中</span>
  </div>
  
  <div class="actions">
    <%= f.submit '登録する' , class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="jumbotron">
	<h1><%= @task.title %></h1>
	<p><%= @task.content %></p>
	<p>期限：<%= @task.deadline %></p>
	<p>担当者：<%= @task.user.name %></p>
	<p>ステータス：<%= display_status(@task.status) %></p>
	<p>
	  <%= link_to '一覧へ戻る', tasks_path, class: 'btn btn-default' %>
	  <% if @task.user == current_user %>
	    <%= link_to '編集', edit_task_path(@task), class: 'btn btn-info' %>
      <%= link_to 'アサイン', assign_task_path(@task), class: 'btn btn-success' %>
    <% end %>
	</p>
</div>